#!/bin/bash

COMMIT_MSG_FILE=${1}
if ! grep -q "^Signed-off-by:" "${COMMIT_MSG_FILE}"; then
    echo "❌ ERROR: Commit aborted."
    echo "Your commit message is missing a 'Signed-off-by:' trailer."
    echo "Please use 'git commit -s' or your custom signoff alias."
    exit 1
fi
